module Django.tproj.Settings

open Fable.Core
open Fable.Core.PyInterop
open Fable.Python

//Django settings for tproj project.
//
//Generated by  "django-admin startproject " using Django 3.2.8.
//
//For more information on this file, see
//https://docs.djangoproject.com/en/3.2/topics/settings/
//
//For the full list of settings and their values, see
//https://docs.djangoproject.com/en/3.2/ref/settings/


[<Emit("__file__")>]
let __file__: string = nativeOnly

[<ImportMember("pathlib")>]
let Path: string -> obj = nativeOnly

// Build paths inside the project like this: BASE_DIR /  "subdir ".
let BASE_DIR:string = Path(__file__)?resolve()?parent?parent

// Quick-start development settings - unsuitable for production
// See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/
//
// SECURITY WARNING: keep the secret key used in production secret!
let SECRET_KEY = "django-insecure-8@-!^t#jw8svblg!%z5meh+#48nvd)me-*^im))uvy6pfweb"
//
// SECURITY WARNING: don "t run with debug turned on in production!
let DEBUG = true

let ALLOWED_HOSTS: string[] = [||]


// Application definition
//
let INSTALLED_APPS = [|
     "django.contrib.admin"
     "django.contrib.auth"
     "django.contrib.contenttypes"
     "django.contrib.sessions"
     "django.contrib.messages"
     "django.contrib.staticfiles"
|]

let MIDDLEWARE = [|
     "django.middleware.security.SecurityMiddleware "
     "django.contrib.sessions.middleware.SessionMiddleware "
     "django.middleware.common.CommonMiddleware "
     "django.middleware.csrf.CsrfViewMiddleware "
     "django.contrib.auth.middleware.AuthenticationMiddleware "
     "django.contrib.messages.middleware.MessageMiddleware "
     "django.middleware.clickjacking.XFrameOptionsMiddleware "
|]

let ROOT_URLCONF = "tproj.urls"

let TEMPLATES: {| APP_DIRS: bool; BACKEND: string; DIRS: string []; OPTIONS: {| context_processors: string [] |} |} [] =
    [|
        {| BACKEND = "django.template.backends.django.DjangoTemplates"
           DIRS= [||]
           APP_DIRS = true
           OPTIONS ={|
                      context_processors=
                         [|
                         "django.template.context_processors.debug"
                         "django.template.context_processors.request"
                         "django.contrib.auth.context_processors.auth"
                         "django.contrib.messages.context_processors.messages"
                        |]
                    |}
           
        |}
    |]

let WSGI_APPLICATION =  "tproj.wsgi.application"

// Database
// https://docs.djangoproject.com/en/3.2/ref/settings/#databases

let DATABASES = {|
     ``default``= {|
                     ENGINE="django.db.backends.sqlite3"
                     NAME = BASE_DIR + "/db.sqlite3"
        |}
|}

// Password validation
// https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

let AUTH_PASSWORD_VALIDATORS = [|
    {|
         NAME="django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
    |}
    {|
         NAME="django.contrib.auth.password_validation.MinimumLengthValidator"
    |}
    {|
         NAME="django.contrib.auth.password_validation.CommonPasswordValidator"
    |}
    {|
         NAME="django.contrib.auth.password_validation.NumericPasswordValidator"
    |}
|]

// Internationalization
// https://docs.djangoproject.com/en/3.2/topics/i18n/

let LANGUAGE_CODE = "en-us"

let TIME_ZONE =  "UTC"

let USE_I18N = true

let USE_L10N = true

let USE_TZ = true

// Static files (CSS, JavaScript, Images)
// https://docs.djangoproject.com/en/3.2/howto/static-files/

let STATIC_URL =  "/static/"

// Default primary key field type
// https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

let DEFAULT_AUTO_FIELD =  "django.db.models.BigAutoField"
