name: Publish NuGet

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  shipit-pr:
    name: ShipIt - Pull Request
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, 'chore: release ')"
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            8.x
            9.x
            10.x

      - name: Install tools
        run: dotnet tool restore

      - name: ShipIt (Pull Request)
        run: dotnet shipit --pre-release rc
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: "startsWith(github.event.head_commit.message, 'chore: release ')"
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            8.x
            9.x
            10.x

      - name: Install just
        uses: extractions/setup-just@v4

      - name: Install tools
        run: |
          dotnet tool restore
          dotnet restore src

      - name: Build, pack and push
        run: just release
        env:
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
